### ISSUE TITLE
Plugin doesn't install

### ISSUE THREAD

**Issue by mattague** [G0ldenSp00n/Wave-Link-Plus#1]
Stream Deck Version: 5.2.0.14948

Issue:
I have downloaded the plugin from the release page, but upon trying to install it nothing happens in the Stream Deck software.

I can give more info if needed, unfortunately i dont know enough about this too contribute much myself so thank you for your work.

**Comment by G0ldenSp00n** [comment]
Did you figure out the issues?  If so can you post how  you resolved to help others in the future?

**Comment by mattague** [comment]
After a restart of my pc and redownload of the plugin it just started working.
