### ISSUE TITLE
"Please update Wave Link to a newer version" - Even though I'm using the latest version

### ISSUE THREAD

**Issue by adamtkwallace** [G0ldenSp00n/Wave-Link-Plus#2]
![image](https://user-images.githubusercontent.com/59363791/176308711-fa9b5fa9-c92a-435a-a4d3-ad7a2cecea9e.png)
![image](https://user-images.githubusercontent.com/59363791/176308766-5c6f699d-c190-4ece-951f-94ccc19e57d0.png)
![image](https://user-images.githubusercontent.com/59363791/176308812-0ad74f81-3c28-490f-a3ef-50650582509f.png)

StreamDeck Plugin asking for me to update Wave Link, yet wave link says it's already up to date? Streamdeck is also up to date. 

Using the latest release of Wave Link Plus

Any ideas?

**Comment by G0ldenSp00n** [comment]
Turns out locally my Wave Link was on the prior version, just forced my Wave Link to update and pushed a new version with the corrected library.  You should be able to get it to work now if you download v0.0.4

**Comment by adamtkwallace** [comment]
Still doesn't work, even with the updated version of your plugin?

**Comment by nicgraner** [comment]
Hi there, just installed the plugin and Im seeing the same issue as shown here. 

Streamdeck software ver: 6.0.0.17703
Streamdeck FW: 1.0.191203

Wavelink Software ver: 1.6.0.2990
WaveXLR FW: 1.3.1

Plugin was just installed today. 

any tips on what to try? 

I did have a couple FW updates, and after updating them, I see the error message in streamdeck is kind of broken: 
![image](https://user-images.githubusercontent.com/36681043/203081170-b0b76a0c-d59a-4b24-87de-24ba985ca213.png)
